// <auto-generated />
using System;
using Fakebook.Posts.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Fakebook.Posts.DataAccess.Migrations
{
    [DbContext(typeof(FakebookPostsContext))]
    partial class FakebookPostsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comment", "Fakebook");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.CommentLike", b =>
                {
                    b.Property<string>("LikerEmail")
                        .HasColumnType("text");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.HasKey("LikerEmail", "CommentId")
                        .HasName("PK_CommentLikes");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentLikes", "Fakebook");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.Follow", b =>
                {
                    b.Property<string>("FollowerEmail")
                        .HasColumnType("text");

                    b.Property<string>("FollowedEmail")
                        .HasColumnType("text");

                    b.HasKey("FollowerEmail", "FollowedEmail")
                        .HasName("PK_UserFollows");

                    b.ToTable("UserFollows", "Fakebook");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Post", "Fakebook");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.PostLike", b =>
                {
                    b.Property<string>("LikerEmail")
                        .HasColumnType("text");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("LikerEmail", "PostId")
                        .HasName("PK_PostLikes");

                    b.HasIndex("PostId");

                    b.ToTable("PostLikes", "Fakebook");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.Comment", b =>
                {
                    b.HasOne("Fakebook.Posts.DataAccess.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Comment_Post")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.CommentLike", b =>
                {
                    b.HasOne("Fakebook.Posts.DataAccess.Models.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FK_Like_Comment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.PostLike", b =>
                {
                    b.HasOne("Fakebook.Posts.DataAccess.Models.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Like_Post")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.Comment", b =>
                {
                    b.Navigation("CommentLikes");
                });

            modelBuilder.Entity("Fakebook.Posts.DataAccess.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
