---
apiVersion: v1
kind: Service
metadata:
  name: fakebook-posts-api
  labels:
    app: fakebook-posts
    role: api
spec:
  ports:
  - port: 80
  selector:
    app: fakebook-posts
    role: api
---
apiVersion: v1
kind: Service
metadata:
  name: fakebook-posts-db
  labels:
    app: fakebook-posts
    role: db
spec:
  ports:
  - port: 5432
  selector:
    app: fakebook-posts
    role: db
